spec-version:                       0.31.0
name:                               satyros
version:                            0.1.0.0
synopsis:                           Step-by-step SAT solver for educational purposes
# description:
category:                           Language
homepage:                           https://github.com/Ailrun/satyros#readme
bug-reports:                        https://github.com/Ailrun/satyros/issues
author:                             Junyoung/Clare Jang
maintainer:                         jjc9310@gmail.com
copyright:                          2021 Junyoung/Clare Jang
license:                            MIT
license-file:                       LICENSE
# tested-with:
# build-type:
extra-source-files:
  - README.md
# extra-doc-files:
# data-files:
# data-dir:
github:                             Ailrun/satyros
# custom-setup:
  # dependencies:

# flags:

library:
  ## Common fields
  source-dirs:
    - src
  dependencies:
    - base
    - containers
    - extra
    - mtl
    - random
    - vector
  ## Library fields
  # exposed:
  # exposed-modules:
  # generated-exposed-modules:
  # other-modules:
  # generated-other-modules:
  # reexported-modules:
  # signatures:

# internal-libraries:

# executable:

tests:
  satyros-test:
    ## Common fields
    source-dirs:
      - test
    ghc-options:                    -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - satyros

      - base
    ## Test fields
    main:                           Spec.hs
    # other-modules:
    # generated-other-modules:

# benchmarks:

# defaults:
  # github:
  # ref:
  # path:
  # local:

## Common fields
# buildable:
# source-dirs:
## Simulate GHC2021 and more
default-extensions:
  BangPatterns
  BinaryLiterals
  ConstrainedClassMethods
  ConstraintKinds
  DeriveDataTypeable
  DeriveFoldable
  DeriveFunctor
  DeriveGeneric
  DeriveLift
  DeriveTraversable
  DerivingStrategies
  EmptyCase
  EmptyDataDecls
  EmptyDataDeriving
  ExistentialQuantification
  ExplicitForAll
  FlexibleContexts
  FlexibleInstances
  ForeignFunctionInterface
  GADTSyntax
  GeneralizedNewtypeDeriving
  HexFloatLiterals
  ImportQualifiedPost
  InstanceSigs
  KindSignatures
  LambdaCase
  MultiParamTypeClasses
  NamedFieldPuns
  NamedWildCards
  NumericUnderscores
  PolyKinds
  PostfixOperators
  RankNTypes
  RecordWildCards
  ScopedTypeVariables
  StandaloneDeriving
  StandaloneKindSignatures
  StarIsType
  TupleSections
  TypeApplications
  TypeFamilies
  TypeOperators
  TypeSynonymInstances
# other-extensions:
ghc-options:
  -Wall -Wcompat -Widentities -Wincomplete-record-updates
  -Wincomplete-uni-patterns -Wmissing-deriving-strategies
  -Wmissing-home-modules -Wmonomorphism-restriction -Wpartial-fields
  -Wredundant-constraints -Wunused-packages -Wunused-type-patterns
# ghc-prof-options:
# ghcjs-options:
# cpp-options:
# cc-options:
# c-sources:
# cxx-options:
# cxx-sources:
# js-sources:
# extra-lib-dirs:
# extra-libraries:
# include-dirs:
# install-includes:
# frameworks:
# extra-frameworks-dirs:
# ld-options:
# dependencies:
# pkg-config-dependencies:
# build-tools:
# system-build-tools:
# when:
